###
GET http://localhost:3000/
###


POST http://localhost:3000/register/ 
Content-Type:application/json 

    {
        "username":"anji",
        "email":"anji123@gmail.com",
        "password":"anji@123",
        "role":"admin"
    }
###
POST http://localhost:3000/login/
Content-Type: application/json 

{
    "email":"anji123@gmail.com",
    "password":"anji@123"
}
###
POST http://localhost:3000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuamkiLCJlbWFpbCI6ImFuamkxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIzMTgzNDQyfQ.YpGFIBb6ZEburCQxKs2ASK3091z0RkaETFAHqQE8jLE

    {
        "title":"paper",
        "description":"this is a paper.",
        "inventoryCount":20
    }
###
GET http://localhost:3000/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmkiLCJlbWFpbCI6InJhdmlrdW1hcjEyMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjI0MTE3NDR9.Ci1JsY2xUZKi7Cuf57nUGeEeIQEQVihtEQXgGG-TP_0
###
PUT http://localhost:3000/products/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmkiLCJlbWFpbCI6InJhdmlrdW1hcjEyMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjI0MTE3NDR9.Ci1JsY2xUZKi7Cuf57nUGeEeIQEQVihtEQXgGG-TP_0

{   
    "title":"fridge",
    "description":"this is a fridge",
    "inventoryCount":75
}
###
DELETE http://localhost:3000/products/2/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmkiLCJlbWFpbCI6InJhdmlrdW1hcjEyMUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjI0MTE3NDR9.Ci1JsY2xUZKi7Cuf57nUGeEeIQEQVihtEQXgGG-TP_0