###
GET https://syoft-node-assignment-2.onrender.com/
###


POST https://syoft-node-assignment-2.onrender.com/register/ 
Content-Type:application/json 

    {
        "username":"mahesh",
        "email":"maesh123@gmail.com",
        "password":"maesh@123",
        "role":"admin"
    }
###
POST https://syoft-node-assignment-2.onrender.com/login/
Content-Type: application/json 

{
    "email":"maesh123@gmail.com",
    "password":"maesh@123"
}
###
POST https://syoft-node-assignment-2.onrender.com/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haGVzaCIsImVtYWlsIjoibWFlc2gxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIzMTg2MzEyfQ.U3gWGUF1qQyfR7NKAs9k-hnMdZ-AclXxyLieEIhL0_o

    {
        "title":"pen",
        "description":"this is a pen.",
        "inventoryCount":50
    }
###
GET https://syoft-node-assignment-2.onrender.com/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haGVzaCIsImVtYWlsIjoibWFlc2gxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIzMTg2MzEyfQ.U3gWGUF1qQyfR7NKAs9k-hnMdZ-AclXxyLieEIhL0_o
###
PUT https://syoft-node-assignment-2.onrender.com/products/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haGVzaCIsImVtYWlsIjoibWFlc2gxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIzMTg2MzEyfQ.U3gWGUF1qQyfR7NKAs9k-hnMdZ-AclXxyLieEIhL0_o

{   
    "title":"fridge",
    "description":"this is a fridge",
    "inventoryCount":75
}
###
DELETE https://syoft-node-assignment-2.onrender.com/products/2/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haGVzaCIsImVtYWlsIjoibWFlc2gxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIzMTg2MzEyfQ.U3gWGUF1qQyfR7NKAs9k-hnMdZ-AclXxyLieEIhL0_o